version: '3.2'
services:
  server:
    build: ssh-server
    depends_on:
      - emq
    links:
      - emq
  emq:
    build: git://github.com/emqtt/emq-docker
    environment:
     - EMQ_NAME=emq
     - EMQ_HOST=127.0.0.1
     - EMQX_LOADED_PLUGINS=emq_dashboard,emq_auth_http
     - EMQX_LOG__CONSOLE__LEVEL=debug
     - EMQ_AUTH__HTTP__AUTH_REQ=http://api:8080/mqtt/auth
     - EMQ_AUTH__HTTP__AUTH_REQ__method=get
     - EMQ_AUTH__HTTP__AUTH_REQ__params=username=%u,password=%P,ipaddr=%a
     - EMQ_AUTH__HTTP__ACL_REQ=http://api:8080/mqtt/acl
     - EMQ_AUTH__HTTP__ACL_REQ__METHOD=get
     - EMQ_AUTH__HTTP__ACL_REQ__PARAMS=access=%A,username=%u,topic=%t,ipaddr=%a
     - EMQ_AUTH__HTTP__ACL_NOMATCH=deny
    links:
      - api
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: host
    - target: 18083
      published: 18083
      protocol: tcp
      mode: host
  web:
    build: web
    depends_on:
      - server
  api:
    build: api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
      mode: host
  mongo:
    image: mongo:3.4.19
